language: python
script:
  - python setup.py -q test
env:  # generate list with: $ tox -l | xargs -I ITEM echo "  - TOXENV="ITEM
  - TOXENV=py26-django15
  - TOXENV=py26-django16
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py32-django15
  - TOXENV=py32-django16
  - TOXENV=py32-django17
  - TOXENV=py32-django18
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
